spring:
  profiles: default
server:
  port: 8010
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles: primary
  application:
    name: eureka-primary
server:
  port: 8011
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
    registerWithEureka: true
    fetchRegistry: true
---

spring:
  profiles: secondary
  application:
    name: eureka-secondary
server:
  port: 8012
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-tertiary:8013/eureka/
    registerWithEureka: true
    fetchRegistry: true
---
spring:
  profiles: tertiary
  application:
    name: eureka-tertiary
server:
  port: 8013
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-secondary:8012/eureka/,http://eureka-primary:8011/eureka/
    registerWithEureka: true
    fetchRegistry: true