spring:
  profiles: primary
  application:
    name: lab-4-eureka-server
server:
  port: 8011
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
    registerWithEureka: true
    fetchRegistry: true
---

spring:
  profiles: secondary
server:
  port: 8012
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-tertiary:8013/eureka/
    registerWithEureka: true
    fetchRegistry: true
---
spring:
  profiles: tertiary
server:
  port: 8013
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-secondary:8012/eureka/,http://eureka-primary:8011/eureka/
    registerWithEureka: true
    fetchRegistry: true